/* ==========================================================
   Gift R — Product catalogue (sample data / demo mode)
   Prices in BDT (৳). Images: images/products/<id>-1.svg … -3.svg
   ========================================================== */

const CATEGORIES = [
  { slug: "birthday", name: "Birthday Gifts", emoji: "🎁", tagline: "Make their big day unforgettable", colors: ["#FFE3EC", "#F9B8CD"] },
  { slug: "anniversary", name: "Anniversary Gifts", emoji: "💑", tagline: "Celebrate love, year after year", colors: ["#FFE0E9", "#F2A0BE"] },
  { slug: "soft-toys", name: "Soft Toys", emoji: "🧸", tagline: "Cuddly friends for every age", colors: ["#FDEBD8", "#E8BE93"] },
  { slug: "flowers", name: "Flowers", emoji: "💐", tagline: "Fresh blooms, delivered with care", colors: ["#FFE5EE", "#F49CBB"] },
  { slug: "personalized", name: "Personalized Gifts", emoji: "🖼️", tagline: "One-of-a-kind, made just for them", colors: ["#FFF0E6", "#F3C89E"] },
  { slug: "cakes", name: "Cakes", emoji: "🎂", tagline: "Sweet treats baked fresh daily", colors: ["#F8E7DC", "#DCAE8C"] },
  { slug: "hampers", name: "Gift Hampers", emoji: "🧺", tagline: "Curated boxes full of surprises", colors: ["#FDEEDA", "#E6C089"] },
  { slug: "perfumes", name: "Perfumes", emoji: "🧴", tagline: "Signature scents they'll adore", colors: ["#F1E8F7", "#C7A6DD"] },
];

const PRODUCTS = [
  /* ---------------- Flowers ---------------- */
  {
    id: "fl01",
    name: "Red Rose Bouquet",
    category: "flowers",
    price: 850,
    oldPrice: 1100,
    rating: 4.9,
    reviews: 214,
    emoji: "🌹",
    colors: ["#FFE0E6", "#F27E9B"],
    badge: "Bestseller",
    featured: true,
    short: "Twenty fresh red roses hand-tied with satin ribbon.",
    description:
      "Twenty premium long-stem red roses, cut the same morning and hand-tied by our florists with black wrapping paper and a red satin ribbon. The classic way to say I love you — perfect for anniversaries, proposals and apologies alike.",
    features: ["20 fresh long-stem red roses", "Hand-tied with satin ribbon", "Free greeting card included", "Same-day delivery in Cumilla"],
  },
  {
    id: "fl02",
    name: "Pink Lily Arrangement",
    category: "flowers",
    price: 1150,
    rating: 4.7,
    reviews: 86,
    emoji: "🌸",
    colors: ["#FFEAF2", "#F0A6C4"],
    short: "Soft pink lilies and baby's breath in a glass vase.",
    description:
      "A calming arrangement of pink oriental lilies and baby's breath, styled in a clear glass vase. The buds keep opening for days, so the gift stays beautiful all week.",
    features: ["8 stems of pink oriental lily", "Baby's breath filler", "Clear glass vase included", "Stays fresh 6–8 days"],
  },
  {
    id: "fl03",
    name: "Mixed Flower Basket",
    category: "flowers",
    price: 1450,
    rating: 4.8,
    reviews: 64,
    emoji: "🧺",
    colors: ["#FFF0E4", "#EFB183"],
    short: "A cane basket packed with seasonal blooms.",
    description:
      "Gerberas, roses, carnations and seasonal fillers arranged in a handmade cane basket. A cheerful choice for get-well wishes, new babies and office openings.",
    features: ["25+ mixed seasonal stems", "Handmade cane basket", "Florist-arranged same day", "Message card included"],
  },

  /* ---------------- Soft Toys ---------------- */
  {
    id: "st01",
    name: "Cute Teddy Bear",
    category: "soft-toys",
    price: 650,
    rating: 4.8,
    reviews: 312,
    emoji: "🧸",
    colors: ["#FDEBD8", "#E3B584"],
    badge: "Bestseller",
    featured: true,
    short: "A 40cm ultra-soft teddy with a red bow.",
    description:
      "Made from hypoallergenic plush that stays soft wash after wash, this 40cm teddy wears a red satin bow and a little heart on its paw. A hug that lasts long after the day is over.",
    features: ["40cm hypoallergenic plush", "Red satin bow", "Child-safe stitched eyes", "Machine washable"],
  },
  {
    id: "st02",
    name: "Giant Panda Plush",
    category: "soft-toys",
    price: 1750,
    oldPrice: 2100,
    rating: 4.9,
    reviews: 98,
    emoji: "🐼",
    colors: ["#F0F0F3", "#BFC3CC"],
    badge: "Sale",
    short: "A huggable 70cm panda that doubles as a pillow.",
    description:
      "Seventy centimetres of squishy panda, filled with premium fibre so it keeps its shape. Big enough to nap on, soft enough to sleep with.",
    features: ["70cm premium fibre fill", "Extra-soft velboa fabric", "Holds its shape for years", "Gift bag included"],
  },
  {
    id: "st03",
    name: "Bunny & Heart Set",
    category: "soft-toys",
    price: 890,
    rating: 4.6,
    reviews: 57,
    emoji: "🐰",
    colors: ["#FFEDF3", "#F1A8C0"],
    short: "A plush bunny holding an embroidered heart cushion.",
    description:
      "A 30cm plush bunny with floppy ears, paired with a small heart cushion embroidered with “Love You”. Presented in a printed gift box ready to hand over.",
    features: ["30cm plush bunny", "Embroidered heart cushion", "Printed gift box", "Great for Valentine's Day"],
  },

  /* ---------------- Personalized ---------------- */
  {
    id: "pz01",
    name: "Personalized Mug",
    category: "personalized",
    price: 450,
    rating: 4.7,
    reviews: 268,
    emoji: "☕",
    colors: ["#EFEFF2", "#B9BCC6"],
    featured: true,
    short: "A ceramic mug printed with any name, photo or message.",
    description:
      "Send us a name, a photo or a short message and we'll print it on a 330ml ceramic mug in full colour. The print is dishwasher-safe and won't fade — a small gift people actually use every morning.",
    features: ["330ml ceramic mug", "Full-colour custom print", "Dishwasher & microwave safe", "Ready in 24 hours"],
  },
  {
    id: "pz02",
    name: "Custom Photo Frame",
    category: "personalized",
    price: 950,
    rating: 4.8,
    reviews: 121,
    emoji: "🖼️",
    colors: ["#FBEEDF", "#DDB489"],
    featured: true,
    short: "A wooden frame engraved with names and a date.",
    description:
      "Your favourite photo printed and set in a solid wood frame, engraved with names, a date or a short quote. Stands on a table or hangs on a wall.",
    features: ["Solid wood frame", "Laser engraving up to 40 characters", "Fits 8×10 inch photo", "Printing included"],
  },
  {
    id: "pz03",
    name: "Name Engraved Keyring Pair",
    category: "personalized",
    price: 550,
    rating: 4.5,
    reviews: 73,
    emoji: "🔑",
    colors: ["#EDE9F6", "#B1A5D6"],
    short: "Two steel keyrings engraved with your chosen names.",
    description:
      "A matching pair of brushed stainless steel keyrings, engraved with two names or initials. A sweet everyday reminder for couples and best friends.",
    features: ["Pair of stainless steel keyrings", "Engraved both sides", "Tarnish resistant", "Velvet pouch included"],
  },

  /* ---------------- Gift Hampers ---------------- */
  {
    id: "hm01",
    name: "Luxury Gift Hamper",
    category: "hampers",
    price: 1650,
    oldPrice: 1950,
    rating: 4.9,
    reviews: 187,
    emoji: "🎁",
    colors: ["#FDEEDA", "#E0B478"],
    badge: "Bestseller",
    featured: true,
    short: "Chocolates, a teddy and treats in a wooden crate.",
    description:
      "Our most-gifted hamper: imported chocolates, dry fruits, a mini teddy, scented candle and a greeting card, packed in a reusable wooden crate and finished with a ribbon. Ready to gift the moment it arrives.",
    features: ["Imported chocolate selection", "Mini teddy & scented candle", "Dry fruits and cookies", "Reusable wooden crate"],
  },
  {
    id: "hm02",
    name: "Chocolate Lover's Box",
    category: "hampers",
    price: 1250,
    rating: 4.8,
    reviews: 142,
    emoji: "🍫",
    colors: ["#F3E2D5", "#C79267"],
    short: "A curated box of imported chocolate bars and truffles.",
    description:
      "Fifteen pieces of imported chocolate — truffles, bars and pralines — arranged in a satin-lined box. The safe choice that never disappoints.",
    features: ["15 imported chocolates", "Satin-lined gift box", "Milk, dark & white varieties", "Gold ribbon finish"],
  },
  {
    id: "hm03",
    name: "Pamper & Spa Hamper",
    category: "hampers",
    price: 1890,
    rating: 4.7,
    reviews: 69,
    emoji: "🧖",
    colors: ["#E9F2EC", "#A6CBB6"],
    badge: "New",
    short: "Bath salts, body butter, candles and herbal tea.",
    description:
      "A self-care hamper with lavender bath salts, shea body butter, two soy candles, a loofah and a box of herbal tea. Perfect for mums, sisters and anyone who needs a quiet evening.",
    features: ["Lavender bath salts & body butter", "2 soy candles", "Herbal tea selection", "Woven gift basket"],
  },

  /* ---------------- Cakes ---------------- */
  {
    id: "ck01",
    name: "Chocolate Cake",
    category: "cakes",
    price: 950,
    rating: 4.9,
    reviews: 256,
    emoji: "🎂",
    colors: ["#F2E0D3", "#C08E63"],
    featured: true,
    short: "A 1kg Belgian chocolate truffle cake.",
    description:
      "One kilogram of rich Belgian chocolate sponge layered with truffle cream and topped with chocolate balls. Baked fresh on the day of delivery and boxed with candles and a knife.",
    features: ["1kg Belgian chocolate cake", "Baked fresh on delivery day", "Candles & knife included", "Eggless option available"],
  },
  {
    id: "ck02",
    name: "Red Velvet Cake",
    category: "cakes",
    price: 1100,
    rating: 4.8,
    reviews: 134,
    emoji: "🍰",
    colors: ["#FBE0E2", "#DC8792"],
    short: "A 1kg red velvet cake with cream cheese frosting.",
    description:
      "Classic red velvet sponge with smooth cream cheese frosting and a crumb finish. Not too sweet — a favourite for birthdays and anniversaries alike.",
    features: ["1kg red velvet sponge", "Cream cheese frosting", "Personalised message on top", "Baked to order"],
  },
  {
    id: "ck03",
    name: "Photo Print Cake",
    category: "cakes",
    price: 1450,
    rating: 4.7,
    reviews: 91,
    emoji: "📸",
    colors: ["#FFF0E0", "#E8BE8A"],
    badge: "New",
    short: "A 1kg vanilla cake topped with an edible photo print.",
    description:
      "Send us a photo and we'll print it in edible ink on a 1kg vanilla or chocolate cake. Ideal for first birthdays, surprise parties and milestone celebrations.",
    features: ["1kg vanilla or chocolate base", "Edible photo print", "Custom message", "24 hours notice required"],
  },

  /* ---------------- Perfumes ---------------- */
  {
    id: "pf01",
    name: "Premium Perfume",
    category: "perfumes",
    price: 1350,
    oldPrice: 1600,
    rating: 4.8,
    reviews: 173,
    emoji: "🧴",
    colors: ["#F0E8F6", "#C0A3D8"],
    badge: "Sale",
    featured: true,
    short: "A 100ml long-lasting eau de parfum in a gift box.",
    description:
      "A warm floral-amber eau de parfum with notes of jasmine, vanilla and sandalwood. 100ml, long lasting on skin and clothes, presented in a black gift box with a ribbon.",
    features: ["100ml eau de parfum", "Jasmine, vanilla & sandalwood", "8+ hours of wear", "Black gift box included"],
  },
  {
    id: "pf02",
    name: "Attar Gift Set",
    category: "perfumes",
    price: 1150,
    rating: 4.7,
    reviews: 88,
    emoji: "🕌",
    colors: ["#F6EEDD", "#D7B679"],
    short: "Three alcohol-free attars in a velvet case.",
    description:
      "Three 6ml alcohol-free attars — oud, musk and rose — in glass roll-on bottles, presented in a velvet case. A thoughtful gift for Eid and family occasions.",
    features: ["3 × 6ml attar bottles", "Oud, musk & rose", "Alcohol free", "Velvet presentation case"],
  },
  {
    id: "pf03",
    name: "Couple Fragrance Duo",
    category: "perfumes",
    price: 2100,
    rating: 4.6,
    reviews: 52,
    emoji: "💞",
    colors: ["#FCE6EF", "#E294B4"],
    short: "His & hers perfume pair in a matching box.",
    description:
      "Two 50ml perfumes designed to complement each other — a fresh aquatic for him and a soft floral for her — packed in one matching gift box.",
    features: ["2 × 50ml perfumes", "Fresh aquatic & soft floral", "Matching gift box", "Popular anniversary pick"],
  },

  /* ---------------- Birthday ---------------- */
  {
    id: "bd01",
    name: "Birthday Surprise Box",
    category: "birthday",
    price: 1550,
    rating: 4.8,
    reviews: 165,
    emoji: "🎁",
    colors: ["#FFE3EC", "#F49BB8"],
    featured: true,
    short: "Balloons, chocolates, candles and a card in one box.",
    description:
      "Open the lid and balloons float out. Inside: chocolates, a scented candle, party poppers, a birthday banner and a handwritten card. The easiest way to surprise someone in another city.",
    features: ["Pop-open balloon box", "Chocolates & party poppers", "Birthday banner & candles", "Handwritten card"],
  },
  {
    id: "bd02",
    name: "Balloon Bouquet",
    category: "birthday",
    price: 750,
    rating: 4.6,
    reviews: 104,
    emoji: "🎈",
    colors: ["#E8EEFF", "#A9BCF0"],
    short: "Twelve helium balloons with a foil number.",
    description:
      "Twelve helium balloons in pink, white and gold with a foil number of your choice, weighted with a small gift box. Floats for up to five days.",
    features: ["12 helium balloons", "Foil age number included", "Weighted gift box base", "Floats up to 5 days"],
  },
  {
    id: "bd03",
    name: "Birthday Mug & Cake Combo",
    category: "birthday",
    price: 1350,
    oldPrice: 1550,
    rating: 4.7,
    reviews: 77,
    emoji: "🥳",
    colors: ["#FFEAD9", "#EEB27E"],
    badge: "Combo",
    short: "A personalized mug with a half-kg chocolate cake.",
    description:
      "A personalized photo mug paired with a 500g chocolate cake, candles and a card — everything needed for a small celebration at home or in the office.",
    features: ["Personalized photo mug", "500g chocolate cake", "Candles & knife", "Free birthday card"],
  },

  /* ---------------- Anniversary ---------------- */
  {
    id: "an01",
    name: "Forever Rose Dome",
    category: "anniversary",
    price: 2250,
    oldPrice: 2600,
    rating: 4.9,
    reviews: 198,
    emoji: "🌹",
    colors: ["#FCE1E8", "#E58BA5"],
    badge: "Premium",
    featured: true,
    short: "A preserved real rose under glass with LED lights.",
    description:
      "A genuine rose, preserved to keep its colour and softness for up to three years, displayed under a glass dome on a wooden base with warm LED fairy lights. No water, no sunlight, no wilting.",
    features: ["Real preserved rose, lasts 3+ years", "Glass dome & wooden base", "Warm LED fairy lights", "Gift box included"],
  },
  {
    id: "an02",
    name: "Couple Photo Lamp",
    category: "anniversary",
    price: 1650,
    rating: 4.8,
    reviews: 112,
    emoji: "💡",
    colors: ["#EAF0FA", "#A8BBD8"],
    short: "A 3D acrylic lamp engraved with your photo.",
    description:
      "Send a couple photo and we'll engrave it into an acrylic panel lit by a wooden LED base with seven colours and a remote. It glows beautifully at night.",
    features: ["3D photo engraving", "7 colours with remote", "Wooden LED base", "USB powered"],
  },
  {
    id: "an03",
    name: "Anniversary Cake & Flowers",
    category: "anniversary",
    price: 1950,
    rating: 4.8,
    reviews: 83,
    emoji: "💐",
    colors: ["#FFE6EE", "#EE9CB9"],
    badge: "Combo",
    short: "A 1kg cake with a dozen red roses, delivered together.",
    description:
      "Our most popular anniversary combo: a 1kg cake of your choice delivered alongside a bouquet of twelve red roses and a greeting card — timed for the moment you choose.",
    features: ["1kg cake (choice of flavour)", "12 red rose bouquet", "Greeting card", "Timed delivery available"],
  },
];

if (typeof module !== "undefined") module.exports = { CATEGORIES, PRODUCTS };
